# Setup
title:        Superyzp's Blog
tagline:      The Technology In Everywhere
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Superyzp
  url:

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
